export const ACCOUNT_DELETE_REASON = {
  GRADUATION: "GRADUATION",
  TRANSFER: "TRANSFER",
  NO_LONGER_NEEDED: "NO_LONGER_NEEDED",
  SERVICE_DISSATISFACTION: "SERVICE_DISSATISFACTION",
  PRIVACY_CONCERN: "PRIVACY_CONCERN",
  OTHER: "OTHER",
} as const;

export type AccountDeleteReason =
  (typeof ACCOUNT_DELETE_REASON)[keyof typeof ACCOUNT_DELETE_REASON];
